### ISSUE TITLE
Not returning rows for certain genes

### ISSUE THREAD

**Issue by zrlewis** [josephryan/alien_index#1]
Hi @josephryan ! Thanks for these scripts and documentation--they've been useful so far. I have a potential issue.

I'm running `alien_index` on some genomes and transcriptomes. The issue that I observe is that even when there are BLAST hits for both ALIEN and non-ALIEN sequences, sometimes genes don't make it into the final `.alien_index` table. I'll paste an example below. 

Here is the blast result:
```
grep model_512402 ../Transcriptome_v_ai.blastp
run_51_model_512402	EDO38482	50.617	81	40	0	20	100	6	86	1.59e-28	102
run_51_model_512402	WHL22.230281.1	53.750	80	37	0	19	98	160	239	3.98e-28	109
run_51_model_512402	SMAR008462-PA	51.899	79	38	0	16	94	4251	4329	3.01e-27	107
run_51_model_512402	CapteP182747	50.649	77	38	0	18	94	10	86	2.58e-25	94.4
run_51_model_512402	HelroP127888	60.606	66	26	0	28	93	2	67	2.74e-25	92.8
run_51_model_512402	PAC:15722443	55.072	69	31	0	26	94	21	89	4.55e-25	93.6
run_51_model_512402	FBpp0084801	56.000	75	33	0	22	96	3	77	5.69e-25	92.8
run_51_model_512402	EFX71227	40.260	77	46	0	22	98	4	80	5.05e-19	78.2
run_51_model_512402	ALIEN_tr|A9UPP6|A9UPP6_MONBE	46.154	65	35	0	28	92	3	67	3.06e-17	72.4
run_51_model_512402	ALIEN_nonmetaCADANIAP00006210	33.750	80	53	0	21	100	10	89	2.15e-13	63.2
run_51_model_512402	TriadP57735	37.681	69	43	0	27	95	21	89	5.18e-13	62.8
run_51_model_512402	ALIEN_nonmetaThaps34186	31.081	74	51	0	27	100	1	74	7.59e-13	61.6
run_51_model_512402	ALIEN_nonmetaPhatr3_J13921.p1	37.179	78	49	0	27	104	1	78	1.43e-12	60.8
run_51_model_512402	ALIEN_CAMPEP_0204466300	32.836	67	45	0	26	92	12	78	3.85e-07	48.1
run_51_model_512402	ALIEN_nonmetaYJR010C-A	32.877	73	41	2	27	95	16	84	3.80e-06	44.7
```

But that gene model doesn't make it into the final `.alien_index` table. Meanwhile, some other genes are working fine. 

For this analysis, I BLASTed 31,303 peptides, which resulted in one or more BLAST hits for 21,848 of them (a total of 3 million BLAST hits). However, the final `.alien_index` table is only 896 lines long. 

Here's my BLAST code and options for running `alien_index`

```
blastp -query proteins.fasta -db ai.fa -outfmt 6 -seg yes -evalue 0.001 -out Transcriptome_v_ai.blastp

perl alien_index --blast=Transcriptome_v_ai.blastp --alien_pattern=ALIEN_ > Transcriptome.alien_index
```

Happy to send over the full BLAST table if that helps with troubleshooting. 

Thanks in advance!
Zack

**Comment by josephryan** [comment]
Hi Zack,
The alien index reflects the difference between the E-value of the best alien BLAST hit and that of the best non-alien hit. You will only receive hits if the top hit is alien. More info on the algorithm is in the README.md and also in Hernandez and Ryan (2018; https://peerj.com/articles/5067/). Let me know if I misunderstood or if you have other questions.
Joe

**Comment by zrlewis** [comment]
>You will only receive hits if the top hit is alien 

Thanks @josephryan, that part wasn't clear to me. Got it now.
